Fix issue #122
steveathon/bootstrap-wysiwyg pull request #123
Opened 2017-05-01 14:26 UTC by floriansegginger

Return the jQuery element in wysiwyg function and expose cleanHtml as a jQuery function.

2017-05-04 18:04 UTC, tylerbhughes commented
Hi @floriansegginger your last commit changes the bower package name for your PR. When your PR gets merged this will affect the repository. Can you set it back to the previous name?

2017-05-04 18:05 UTC, floriansegginger commented
I’m sorry, I got a bit confused trying to make my own bower repo .. this is my first time doing this :)

I don’t really care too much about the credit. Since this is a small change maybe you can make the commit yourself?

-- 
	
Florian Segginger
Co-founder, Fullrange Interactive Sàrl
+41 79 375 65 66
florian@fullrange.ch <mailto:florian@fullrange.ch> | f@floriansegginger.ch <mailto:f@floriansegginger.ch>
Facebook <http://www.facebook.com/fullrangeinteractive> | www.fullrange.ch <http://www.fullrange.ch/>
> On 4 May 2017, at 20:04, Tyler Hughes <notifications@github.com> wrote:
> 
> Hi @floriansegginger <https://github.com/floriansegginger> your last commit changes the bower package name for your PR. When your PR gets merged this will affect the repository. Can you set it back to the previous name?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/steveathon/bootstrap-wysiwyg/pull/123#issuecomment-299263775>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ADGDKSefYJX5kAVQJ8iRSlnLS-mev9rZks5r2hMfgaJpZM4NNFIF>.
>

2018-03-10 06:51 UTC, steveathon requested changes
Hi,

I think in general your change for adding the cleanHTML function seems sane, but I can't approve it with the updated bower. 

Can we strip out the change and edit it in?

2018-03-10 06:51 UTC, steveathon commented on bower.json
> +  "name": "floriansegginger-bootstrap-wysiwyg",
This can't merge into the main package.

2018-03-10 06:51 UTC, steveathon commented on bower.json
> +  "version": "2.1.0",
This can't merge into the main package.

2018-03-10 06:51 UTC, steveathon commented on bower.json
> +  "homepage": "https://github.com/floriansegginger/bootstrap-wysiwyg",
This can't merge into the main package.

2018-03-21 16:49 UTC, mhagnumdw commented
When will the next version come out? I use version 2.0.1 and I can not access cleanHtml. Tks!

2018-08-15 06:24 UTC, steveathon reviewed
Overall I'm happy to merge this I'm just waiting for the reviewed changes. Either I'll wait for this update, or I'll cherry pick the update.

2018-08-15 06:24 UTC, steveathon commented on bower.json
> +  "name": "floriansegginger-bootstrap-wysiwyg",
Can you update this so we can merge?

2018-08-15 06:24 UTC, steveathon commented on bower.json
> +  "version": "2.1.0",
Also this.

2018-08-15 06:24 UTC, steveathon commented on bower.json
> +  "homepage": "https://github.com/floriansegginger/bootstrap-wysiwyg",
Also this.

2018-08-15 06:31 UTC, steveathon commented
Only just saw your other comment, apologies @floriansegginger - I've created the branch /cleanHTML and I'll be updating it shortly.

Thanks for your contribution!

2018-08-15 06:31 UTC, closed without merging